// Language switcher
const translations = {
  es: {
    panel: 'Panel',
    dashboard: 'Dashboard',
    camaras: 'Cámaras',
    personas: 'Personas',
    vehiculos: 'Vehículos',
    alertas: 'Alertas',
    baseDatos: 'Base de Datos',
    reportes: 'Reportes',
    deteccionVivo: 'Detección en Vivo',
    diagnostico: 'Diagnóstico',
    conectarCliente: 'Conectar con el Servidor',
    accesoRemoto: 'ACCESO REMOTO',
    accesoLocal: 'ACCESO LOCAL',
    ipPublica: 'IP Pública:',
    urlRemota: 'URL Remota:',
    ipLocal: 'IP Local:',
    urlLocal: 'URL Local:',
    copiar: 'Copiar',
    deteccionesPorTipo: 'Detecciones por Tipo',
    vehiculosDetectados: 'Vehículos Detectados',
    estadoDelSistema: 'Estado del Sistema',
    statusApi: 'Status API',
    online: 'Online',
    baseDatos: 'Base de Datos',
    miPerfil: 'Mi Perfil',
    editarInformacion: 'Editar Información Personal',
    nombre: 'Nombre:',
    apellido: 'Apellido:',
    email: 'Email:',
    telefono: 'Teléfono:',
    departamento: 'Departamento:',
    rol: 'Rol:',
    guardarCambios: 'Guardar Cambios',
    cancelar: 'Cancelar',
    cambiosGuardados: 'Cambios guardados exitosamente',
    verPerfil: 'Ver perfil',
    cerrarSesion: 'Cerrar sesión',
    lineaTemporal: 'Línea Temporal',
    // Perfil — contacto y alertas
    infoContacto: 'Información de Contacto',
    emailHint: 'Usado para recibir alertas por email',
    phoneHint: 'Usado para recibir alertas por SMS/llamada',
    guardarContacto: 'Guardar contacto',
    prefAlertas: 'Preferencias de Alertas',
    alertasEmail: 'Alertas por email',
    alertasEmailDesc: 'Recibir notificaciones al correo configurado',
    alertasCriticas: 'Alertas críticas',
    alertasCriticasDesc: 'Intrusos, violaciones de perímetro',
    alertasWarning: 'Alertas de advertencia',
    alertasWarningDesc: 'Movimiento inusual, cámara offline',
    alertasTel: 'Alertas por teléfono / SMS',
    alertasTelDesc: 'Recibir notificaciones al número configurado',
    guardarPreferencias: 'Guardar preferencias',
    cambiarPass: 'Cambiar Contraseña',
    passActual: 'Contraseña actual',
    passNueva: 'Nueva contraseña',
    passConfirmar: 'Confirmar contraseña',
    cambiarPassBtn: 'Cambiar contraseña',
    resumenCuenta: 'Cuenta',
    resumenSeguridad: 'Seguridad',
    labelUsuario: 'Usuario:',
    labelRol: 'Rol:',
    labelCreado: 'Creado:',
    label2fa: '2FA:',
    labelEmailNotif: 'Email alertas:',
    labelTelNotif: 'Tel. alertas:',
    // Perfil — campos de tabla y botones
    cambiarFoto: 'Cambiar foto',
    expandir: 'Expandir',
    editar: 'Editar',
    guardar: 'Guardar',
    labelUsuarioTable: 'Usuario',
    labelNombreVisible: 'Nombre visible',
    labelRolTable: 'Rol',
    labelEmailTable: 'Email',
    labelTelefonoTable: 'Teléfono',
    labelMiembroDesde: 'Miembro desde',
    twoFaActivo: 'Activo',
    twoFaInactivo: 'Inactivo',
    adminRole: 'Administrador',
    operatorRole: 'Operador',
    viewerRole: 'Visualizador',
    sinCorreo: '(sin correo)',
    sinTelefono: '(sin teléfono)',
    // Dashboard — conectar cliente
    conectarClienteCard: 'Conectar Cliente',
    camaraPublica: 'CÁMARA PÚBLICA (HTTPS)',
    urlLabel: 'URL:',
    abrir: 'Abrir',
    // Dashboard — recursos del servidor
    recursosServidor: 'Recursos del Servidor',
    fechaHora: 'Fecha / Hora',
    estado: 'Estado',
    sistemaActivo: 'Sistema activo',
    ramSistema: 'RAM sistema',
    ramProceso: 'RAM proceso',
    usoProcesoPython: 'Uso del proceso Python',
    disco: 'Disco',
    redEnviado: 'Red ↑ enviado',
    redRecibido: 'Red ↓ recibido',
    colaYolo: 'Cola YOLO',
    framesUnit: 'frames',
    hilosActivos: 'Hilos activos',
    threadsPython: 'Threads Python',
    // Dashboard — estado e historial
    deteccionesRealTime: 'Detecciones en tiempo real',
    esperandoDatos: 'Esperando datos…',
    onlineText: '● Online',
    servidor: 'Servidor',
    conectado: 'Conectado',
    activoText: 'Activo',
    cargando: 'Cargando...',
    // Dashboard — tarjetas estadísticas
    camarasStat: 'Cámaras',
    personasStat: 'Personas',
    vehiculosStat: 'Vehículos',
    alertasStat: 'Alertas',
    ultimasDetecciones: 'Últimas Detecciones',
    // Dashboard — secciones adicionales
    detecciones: 'Detecciones',
    deteccionIA: 'Detección IA',
    sslHttps: 'SSL / HTTPS',
    webSocket: 'WebSocket',
    cpuProceso: 'CPU Proceso',
    usoCpuPython: 'Uso CPU Python',
    discoES: 'Disco E/S',
    historialClientes: 'Historial de Clientes',
    actualizarBtn: 'Actualizar',
    idNombre: 'ID / Nombre',
    primeraConexion: 'Primera conexión',
    ultimaActividad: 'Última actividad',
    feedsDirecto: 'Feeds en Directo',
    actualizacion: 'Actualización',
    recargar: 'Recargar',
    deteccionesRT: 'Detecciones en Tiempo Real',
    horaCol: 'Hora',
    camaraCol: 'Cámara',
    tipoCol: 'Tipo',
    confianzaCol: 'Confianza',
    posicionCol: 'Posición',
    esperandoDetecciones: 'Esperando detecciones... Conecta una cámara.',
    fotoCol: 'Foto',
    idDescripcion: 'ID / Descripción',
    vecesCol: 'Veces',
    fechaHoraCol: 'Fecha y Hora',
    alertasSistema: 'Alertas del Sistema',
    todosFilter: 'Todos',
    criticasFilter: 'Críticas',
    advertenciasFilter: 'Advertencias',
    informacionFilter: 'Información',
    tablasBD: 'Tablas',
    consultaSQL: 'Consulta SQL',
    consultasSimplificadas: 'Consultas Simplificadas',
    tablasBDTitle: 'Tablas de la Base de Datos',
    consultaSQLTitle: 'Consulta SQL (solo lectura)',
    ejecutar: 'Ejecutar',
    limpiar: 'Limpiar',
    generarReporte: 'Generar Reporte',
    desdeLabel: 'Desde',
    hastaLabel: 'Hasta',
    tipoLabel: 'Tipo',
    formatoLabel: 'Formato',
    vistaPrevia: 'Vista previa',
    descargar: 'Descargar',
    camFeedLive: 'En directo',
    camFeedAI: 'IA · YOLO',
    camFeedZoomHint: 'Rueda: zoom · Doble clic: reset',
    // Timeline
    seleccionarRango: 'Seleccionar rango de tiempo',
    buscarBtn: 'Buscar',
  },
  en: {
    panel: 'Panel',
    dashboard: 'Dashboard',
    camaras: 'Cameras',
    personas: 'People',
    vehiculos: 'Vehicles',
    alertas: 'Alerts',
    baseDatos: 'Database',
    reportes: 'Reports',
    deteccionVivo: 'Live Detection',
    diagnostico: 'Diagnostics',
    conectarCliente: 'Connect to Server',
    accesoRemoto: 'REMOTE ACCESS',
    accesoLocal: 'LOCAL ACCESS',
    ipPublica: 'Public IP:',
    urlRemota: 'Remote URL:',
    ipLocal: 'Local IP:',
    urlLocal: 'Local URL:',
    copiar: 'Copy',
    deteccionesPorTipo: 'Detections by Type',
    vehiculosDetectados: 'Detected Vehicles',
    estadoDelSistema: 'System Status',
    statusApi: 'API Status',
    online: 'Online',
    baseDatos: 'Database',
    miPerfil: 'My Profile',
    editarInformacion: 'Edit Personal Information',
    nombre: 'First Name:',
    apellido: 'Last Name:',
    email: 'Email:',
    telefono: 'Phone:',
    departamento: 'Department:',
    rol: 'Role:',
    guardarCambios: 'Save Changes',
    cancelar: 'Cancel',
    cambiosGuardados: 'Changes saved successfully',
    verPerfil: 'View profile',
    cerrarSesion: 'Logout',
    lineaTemporal: 'Timeline',
    // Profile — contact & alerts
    infoContacto: 'Contact Information',
    emailHint: 'Used to receive email alerts',
    phoneHint: 'Used to receive SMS/call alerts',
    guardarContacto: 'Save contact',
    prefAlertas: 'Alert Preferences',
    alertasEmail: 'Email alerts',
    alertasEmailDesc: 'Receive notifications to the configured email',
    alertasCriticas: 'Critical alerts',
    alertasCriticasDesc: 'Intruders, perimeter violations',
    alertasWarning: 'Warning alerts',
    alertasWarningDesc: 'Unusual movement, camera offline',
    alertasTel: 'Phone / SMS alerts',
    alertasTelDesc: 'Receive notifications to the configured number',
    guardarPreferencias: 'Save preferences',
    cambiarPass: 'Change Password',
    passActual: 'Current password',
    passNueva: 'New password',
    passConfirmar: 'Confirm password',
    cambiarPassBtn: 'Change password',
    resumenCuenta: 'Account',
    resumenSeguridad: 'Security',
    labelUsuario: 'User:',
    labelRol: 'Role:',
    labelCreado: 'Created:',
    label2fa: '2FA:',
    labelEmailNotif: 'Email alerts:',
    labelTelNotif: 'Phone alerts:',
    // Profile — table fields and buttons
    cambiarFoto: 'Change photo',
    expandir: 'Expand',
    editar: 'Edit',
    guardar: 'Save',
    labelUsuarioTable: 'Username',
    labelNombreVisible: 'Display name',
    labelRolTable: 'Role',
    labelEmailTable: 'Email',
    labelTelefonoTable: 'Phone',
    labelMiembroDesde: 'Member since',
    twoFaActivo: 'Active',
    twoFaInactivo: 'Inactive',
    adminRole: 'Administrator',
    operatorRole: 'Operator',
    viewerRole: 'Viewer',
    sinCorreo: '(no email)',
    sinTelefono: '(no phone)',
    // Dashboard — connect client
    conectarClienteCard: 'Connect Client',
    camaraPublica: 'PUBLIC CAMERA (HTTPS)',
    urlLabel: 'URL:',
    abrir: 'Open',
    // Dashboard — server resources
    recursosServidor: 'Server Resources',
    fechaHora: 'Date / Time',
    estado: 'Status',
    sistemaActivo: 'System active',
    ramSistema: 'System RAM',
    ramProceso: 'Process RAM',
    usoProcesoPython: 'Python process usage',
    disco: 'Disk',
    redEnviado: 'Net ↑ sent',
    redRecibido: 'Net ↓ received',
    colaYolo: 'YOLO queue',
    framesUnit: 'frames',
    hilosActivos: 'Active threads',
    threadsPython: 'Python threads',
    // Dashboard — status and history
    deteccionesRealTime: 'Real-time detections',
    esperandoDatos: 'Waiting for data…',
    onlineText: '● Online',
    servidor: 'Server',
    conectado: 'Connected',
    activoText: 'Active',
    cargando: 'Loading...',
    // Dashboard — stat cards
    camarasStat: 'Cameras',
    personasStat: 'People',
    vehiculosStat: 'Vehicles',
    alertasStat: 'Alerts',
    ultimasDetecciones: 'Latest Detections',
    // Dashboard — additional sections
    detecciones: 'Detections',
    deteccionIA: 'AI Detection',
    sslHttps: 'SSL / HTTPS',
    webSocket: 'WebSocket',
    cpuProceso: 'Process CPU',
    usoCpuPython: 'Python CPU Usage',
    discoES: 'Disk I/O',
    historialClientes: 'Client History',
    actualizarBtn: 'Refresh',
    idNombre: 'ID / Name',
    primeraConexion: 'First Connection',
    ultimaActividad: 'Last Activity',
    feedsDirecto: 'Live Feeds',
    actualizacion: 'Update rate',
    recargar: 'Reload',
    deteccionesRT: 'Real-Time Detections',
    horaCol: 'Time',
    camaraCol: 'Camera',
    tipoCol: 'Type',
    confianzaCol: 'Confidence',
    posicionCol: 'Position',
    esperandoDetecciones: 'Waiting for detections... Connect a camera.',
    fotoCol: 'Photo',
    idDescripcion: 'ID / Description',
    vecesCol: 'Count',
    fechaHoraCol: 'Date & Time',
    alertasSistema: 'System Alerts',
    todosFilter: 'All',
    criticasFilter: 'Critical',
    advertenciasFilter: 'Warnings',
    informacionFilter: 'Info',
    tablasBD: 'Tables',
    consultaSQL: 'SQL Query',
    consultasSimplificadas: 'Simplified Queries',
    tablasBDTitle: 'Database Tables',
    consultaSQLTitle: 'SQL Query (read-only)',
    ejecutar: 'Execute',
    limpiar: 'Clear',
    generarReporte: 'Generate Report',
    desdeLabel: 'From',
    hastaLabel: 'To',
    tipoLabel: 'Type',
    formatoLabel: 'Format',
    vistaPrevia: 'Preview',
    descargar: 'Download',
    camFeedLive: 'Live',
    camFeedAI: 'AI · YOLO',
    camFeedZoomHint: 'Wheel: zoom · Double-click: reset',
    // Timeline
    seleccionarRango: 'Select time range',
    buscarBtn: 'Search',
  },
  jp: {
    panel: 'パネル',
    dashboard: 'ダッシュボード',
    camaras: 'カメラ',
    personas: '人物',
    vehiculos: '車両',
    alertas: 'アラート',
    baseDatos: 'データベース',
    reportes: 'レポート',
    deteccionVivo: 'ライブ検出',
    diagnostico: '診断',
    conectarCliente: 'サーバーに接続',
    accesoRemoto: 'リモートアクセス',
    accesoLocal: 'ローカルアクセス',
    ipPublica: 'パブリックIP:',
    urlRemota: 'リモートURL:',
    ipLocal: 'ローカルIP:',
    urlLocal: 'ローカルURL:',
    copiar: 'コピー',
    deteccionesPorTipo: '検出タイプ別',
    vehiculosDetectados: '検出された車両',
    estadoDelSistema: 'システムステータス',
    statusApi: 'APIステータス',
    online: 'オンライン',
    baseDatos: 'データベース',
    miPerfil: 'マイプロフィール',
    editarInformacion: '個人情報の編集',
    nombre: '名前:',
    apellido: '姓:',
    email: 'メール:',
    telefono: '電話:',
    departamento: '部門:',
    rol: '役割:',
    guardarCambios: '変更を保存',
    cancelar: 'キャンセル',
    cambiosGuardados: '変更が正常に保存されました',
    verPerfil: 'プロフィール表示',
    cerrarSesion: 'ログアウト',
    lineaTemporal: 'タイムライン',
    // プロフィール — 連絡先・アラート
    infoContacto: '連絡先情報',
    emailHint: 'メールアラートの受信に使用',
    phoneHint: 'SMS/電話アラートの受信に使用',
    guardarContacto: '連絡先を保存',
    prefAlertas: 'アラート設定',
    alertasEmail: 'メールアラート',
    alertasEmailDesc: '設定したメールに通知を受け取る',
    alertasCriticas: '重大アラート',
    alertasCriticasDesc: '侵入者、境界線違反',
    alertasWarning: '警告アラート',
    alertasWarningDesc: '異常な動き、カメラオフライン',
    alertasTel: '電話 / SMS アラート',
    alertasTelDesc: '設定した番号に通知を受け取る',
    guardarPreferencias: '設定を保存',
    cambiarPass: 'パスワード変更',
    passActual: '現在のパスワード',
    passNueva: '新しいパスワード',
    passConfirmar: 'パスワード確認',
    cambiarPassBtn: 'パスワードを変更',
    resumenCuenta: 'アカウント',
    resumenSeguridad: 'セキュリティ',
    labelUsuario: 'ユーザー:',
    labelRol: '役割:',
    labelCreado: '作成日:',
    label2fa: '2FA:',
    labelEmailNotif: 'メールアラート:',
    labelTelNotif: '電話アラート:',
    // プロフィール — テーブルフィールドとボタン
    cambiarFoto: '写真を変更',
    expandir: '展開',
    editar: '編集',
    guardar: '保存',
    labelUsuarioTable: 'ユーザー名',
    labelNombreVisible: '表示名',
    labelRolTable: '役割',
    labelEmailTable: 'メール',
    labelTelefonoTable: '電話',
    labelMiembroDesde: 'メンバー登録日',
    twoFaActivo: '有効',
    twoFaInactivo: '無効',
    adminRole: '管理者',
    operatorRole: 'オペレーター',
    viewerRole: '閲覧者',
    sinCorreo: '(メールなし)',
    sinTelefono: '(電話なし)',
    // ダッシュボード — クライアント接続
    conectarClienteCard: 'クライアント接続',
    camaraPublica: 'パブリックカメラ (HTTPS)',
    urlLabel: 'URL:',
    abrir: '開く',
    // ダッシュボード — サーバーリソース
    recursosServidor: 'サーバーリソース',
    fechaHora: '日時',
    estado: '状態',
    sistemaActivo: 'システム稼働中',
    ramSistema: 'システムRAM',
    ramProceso: 'プロセスRAM',
    usoProcesoPython: 'Pythonプロセス使用量',
    disco: 'ディスク',
    redEnviado: 'ネット ↑ 送信',
    redRecibido: 'ネット ↓ 受信',
    colaYolo: 'YOLOキュー',
    framesUnit: 'フレーム',
    hilosActivos: 'アクティブスレッド',
    threadsPython: 'Pythonスレッド',
    // ダッシュボード — ステータスと履歴
    deteccionesRealTime: 'リアルタイム検出',
    esperandoDatos: 'データ待機中…',
    onlineText: '● オンライン',
    servidor: 'サーバー',
    conectado: '接続済み',
    activoText: 'アクティブ',
    cargando: '読み込み中...',
    // ダッシュボード — 統計カード
    camarasStat: 'カメラ',
    personasStat: '人物',
    vehiculosStat: '車両',
    alertasStat: 'アラート',
    ultimasDetecciones: '最新の検出',
    // ダッシュボード — 追加セクション
    detecciones: '検出',
    deteccionIA: 'AI 検出',
    sslHttps: 'SSL / HTTPS',
    webSocket: 'WebSocket',
    cpuProceso: 'プロセス CPU',
    usoCpuPython: 'Python CPU使用量',
    discoES: 'ディスク I/O',
    historialClientes: 'クライアント履歴',
    actualizarBtn: '更新',
    idNombre: 'ID / 名前',
    primeraConexion: '初回接続',
    ultimaActividad: '最終活動',
    feedsDirecto: 'ライブフィード',
    actualizacion: '更新レート',
    recargar: '再読み込み',
    deteccionesRT: 'リアルタイム検出',
    horaCol: '時刻',
    camaraCol: 'カメラ',
    tipoCol: 'タイプ',
    confianzaCol: '信頼度',
    posicionCol: '位置',
    esperandoDetecciones: '検出待機中... カメラを接続してください。',
    fotoCol: '写真',
    idDescripcion: 'ID / 説明',
    vecesCol: '回数',
    fechaHoraCol: '日時',
    alertasSistema: 'システムアラート',
    todosFilter: 'すべて',
    criticasFilter: '重大',
    advertenciasFilter: '警告',
    informacionFilter: '情報',
    tablasBD: 'テーブル',
    consultaSQL: 'SQL クエリ',
    consultasSimplificadas: '簡易クエリ',
    tablasBDTitle: 'データベーステーブル',
    consultaSQLTitle: 'SQL クエリ（読み取り専用）',
    ejecutar: '実行',
    limpiar: 'クリア',
    generarReporte: 'レポート生成',
    desdeLabel: '開始',
    hastaLabel: '終了',
    tipoLabel: 'タイプ',
    formatoLabel: 'フォーマット',
    vistaPrevia: 'プレビュー',
    descargar: 'ダウンロード',
    camFeedLive: 'ライブ',
    camFeedAI: 'AI · YOLO',
    camFeedZoomHint: 'ホイール: ズーム · ダブルクリック: リセット',
    // タイムライン
    seleccionarRango: '時間範囲を選択',
    buscarBtn: '検索',
  }
};

let currentLang = localStorage.getItem('language') || 'es';

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('language', lang);
  console.log('Idioma cambiado a:', lang);
  
  // Update flag display
  const flagMap = {
    es: '/static/img/flag-es.svg',
    en: '/static/img/flag-en.svg',
    jp: '/static/img/flag-jp.svg'
  };
  
  const flagDisplay = document.getElementById('langFlagDisplay');
  if (flagDisplay) {
    flagDisplay.src = flagMap[lang];
    flagDisplay.alt = lang;
  }
  
  // Update page texts
  updatePageTexts();
}

function updatePageTexts() {
  const elements = document.querySelectorAll('[data-i18n]');
  console.log('Elementos encontrados con data-i18n:', elements.length);
  
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[currentLang] && translations[currentLang][key]) {
      el.textContent = translations[currentLang][key];
    }
  });
}

document.addEventListener('DOMContentLoaded', () => {
  console.log('[Language] Inicializando sistema de idiomas...');
  
  const languageBtn = document.getElementById('languageBtn');
  const languageDropdown = document.getElementById('languageDropdown');
  const langItems = document.querySelectorAll('#languageDropdown .dropdown-item');

  console.log('Botón idioma:', languageBtn ? 'OK' : 'NO ENCONTRADO');
  console.log('Dropdown idioma:', languageDropdown ? 'OK' : 'NO ENCONTRADO');
  console.log('Items idioma:', langItems.length);

  if (!languageBtn || !languageDropdown) {
    console.warn('[Language] Elementos no encontrados');
    return;
  }

  // Toggle language dropdown
  languageBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    console.log('Abriendo dropdown de idioma');
    languageDropdown.classList.toggle('hidden');
  });

  // Handle language selection
  langItems.forEach(item => {
    item.addEventListener('click', (e) => {
      e.stopPropagation();
      const lang = item.getAttribute('data-lang');
      console.log('Seleccionado idioma:', lang);
      setLanguage(lang);
      languageDropdown.classList.add('hidden');
    });
  });

  // Close dropdown when clicking outside
  document.addEventListener('click', (e) => {
    if (!languageBtn.contains(e.target) && !languageDropdown.contains(e.target)) {
      languageDropdown.classList.add('hidden');
    }
  });

  // Initialize with saved language
  console.log('Idioma inicial:', currentLang);
  setLanguage(currentLang);
  
  console.log('[Language] Sistema de idiomas inicializado ✓');
});
